export const homeOptions = [
  "As a software engineer specializing in full-stack web development Myexpertise includes front-end technologies such as JavaScript,TypeScript, Node.js, HTML, CSS/Sass, and jQuery, as well as popularfrontend frameworks such as React, React Native, and Vue.",
  "I have extensive experience with a variety of frontend tools andlibraries, including React Query, Redux, Material UI, and Vuetify,and am skilled in building asynchronous APIs to support dynamic andresponsive web applications.",
  "On the backend, I am proficient in using Express.js to build robustand scalable server-side applications. I also have experienceworking with popular server-side frameworks such as Next.js andRemix.js, which allow me to create server-side rendered webapplications that offer a seamless user experience.",
  "I am highly skilled in using Git for version control, and haveworked with a range of version control platforms including GitLab,GitHub, and Bitbucket. In terms of databases, I am experienced withboth SQL and MongoDB, as well as Firebase, and am well-versed indesigning and implementing efficient data storage and retrievalmechanisms.",
  "Additionally, I am familiar with other programming languages andframeworks such as Python, Java, and Spring Boot. In addition to webdevelopment, I am am always looking for ways to expand my knowledgeand skills about cloud technologies and services. I have experienceworking with Amazon Web Services (AWS), including using servicessuch as RDS and EC2 to manage databases and instances in the cloud.",
  "I am skilled in using Docker and containers to deploy applications,and am familiar with tools such as Jenkins for continuousintegration and deployment. You can take a look at my GitHub profileto see some examples of my work and projects that I have contributedto.",
  "As a software engineer, I am always looking for new challenges andopportunities to apply my skills, and I am passionate about creatinghigh-quality software that meets the needs of users and businessesalike always applying best practices.",
];
